services:
  nginx:
    build: ./nginx
    container_name: infra_nginx
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress

  wordpress:
    build: ./wordpress
    container_name: infra_wordpress
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: mysqldb
      WORDPRESS_DB_USER: mysqluser
      WORDPRESS_DB_PASSWORD: mysqlpass
    volumes:
      - ./wordpress/data:/var/www/html
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    container_name: infra_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
    volumes:
      - ./mysql/data:/var/lib/mysql
