apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data/wordpress
