apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.nginx.appName }}-exporter
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.nginx.appName }}
  ports:
    - name: {{ .Values.nginx.exporter.name }}
      port: {{ .Values.nginx.exporter.port }}
      targetPort: {{ .Values.nginx.exporter.servicePort }}
