apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.mysql.appName }}
  ports:
    - port: {{ .Values.mysql.containerPort }}
      targetPort: {{ .Values.mysql.servicePort }}
